image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.8.0

variables:
    MAVEN_OPTS: -Dmaven.repo.local=/cache
    IMAGE_VERSION: 1.3.0
    RANCHER_CLI_IMAGES: registry.cloud.saas.hand-china.com/hcf/jonaskello/rancher-cli-k8s:v2.0.4
stages:
- build
- dev-build
- dev-deploy
- test-build
- test-deploy
- prod-build
- prod-deploy
build:
    stage: build
    except:
    - /^dev-.*$/
    - /^release-.*$/
    - /^test-.*$/
    - master
    - /^v.*$/
    script:
    - "mvn -U clean compile"
    - "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package -Dmaven.test.failure.ignore=true -DskipTests=false -Dsecurity.oauth2.client.access-token-uri=http://101.132.162.31:9081/auth/oauth/token -Dsecurity.oauth2.resource.user-info-uri=http://101.132.162.31:9081/auth/api/check_token -Dapollo.bootstrap.namespaces=common,application -Dspring.datasource.url=jdbc:oracle:thin:@47.101.143.73:1521/hcfuatp1 -Deureka.client.enabled=false -Denv=dev -Dapollo.meta=http://139.196.136.154:8180 -Dspring.redis.host=47.101.58.187 -U"
    - "mvn -DskipTests=true --batch-mode verify sonar:sonar -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONARQUBE_TOKEN -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID"


dev-build:
    stage: dev-build
    only:
    - tags
    except:
    - /^test-.*$/
    - master
    - /^v.*$/
    script:
    - build_image $IMAGE_VERSION-

dev-deploy:
    stage: dev-deploy
    image: $RANCHER_CLI_IMAGES
    only:
    - tags
    except:
    - /^test-.*$/
    - master
    - /^v.*$/
    script:
    - deploy_image $RANCHER_DEV_PROJECT_ID dev default $IMAGE_VERSION-

test-build:
    stage: test-build
    only:
    - tags
    except:
    - /^dev-.*$/
    - master
    - /^v.*$/
    script:
    - build_image $IMAGE_VERSION-

test-deploy:
    stage: test-deploy
    image: $RANCHER_CLI_IMAGES
    only:
    - tags
    except:
    - /^dev-.*$/
    - master
    - /^v.*$/
    script:
    - deploy_image $RANCHER_TEST_PROJECT_ID test test-default $IMAGE_VERSION-


prod-build:
    stage: prod-build
    only:
    - tags
    except:
    - /^dev-.*$/
    - /^test-.*$/
    script:
    - build_image

prod-deploy:
    stage: prod-deploy
    image: $RANCHER_CLI_IMAGES
    only:
    - tags
    except:
    - /^dev-.*$/
    - /^test-.*$/
    script:
    - deploy_image $RANCHER_PROD_PROJECT_ID prod default

.auto_devops: &auto_devops |

    function build_image(){
        mvn compile jib:build \
        -Dimage_tag=${1}$CI_COMMIT_REF_NAME  \
        -Dregistry_url=$REGISTRY_URL \
        -Dregistry_username=$REGISTRY_USERNAME \
        -Dregistry_password=$REGISTRY_PASSWORD
    }

    function deploy_image(){
        echo yes | rancher login $RANCHER_URL -t $RANCHER_TOKEN --context ${1}
        sed -i 's^${registry_url}^'"$REGISTRY_URL^g" "./deployment-${2}.yaml"
        sed -i 's^${image_tag}^'"${4}$CI_COMMIT_REF_NAME^g" "./deployment-${2}.yaml"
        rancher kubectl --namespace=${3} apply -f ./deployment-${2}.yaml
    }

before_script:
- *auto_devops