apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: fund-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-fund-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-05-04T07:50:47Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-fund-service
    spec:
      containers:
      - env:
        - name: EUREKA_DEFAULT_ZONE
          value: http://admin:admin@registerPeer1:9070/eureka,http://admin:admin@registerPeer2:9071/eureka
        - name: JAVA_TOOL_OPTIONS
          value: -Xmx512m -Dapollo.meta=http://139.196.136.154:8180 -Dapollo.bootstrap.namespaces=common,application
        image: ${registry_url}/hcf/fund-service:${image_tag}
        imagePullPolicy: Always
        name: fund-service
        resources:
          limits:
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
